Change IMAGE_TAG dev reference

diff --git a/.github/workflows/Procedure_push_docker_images.yml b/.github/workflows/Procedure_push_docker_images.yml
--- a/.github/workflows/Procedure_push_docker_images.yml
+++ b/.github/workflows/Procedure_push_docker_images.yml
@@ -152,26 +152,21 @@ jobs:
 
     - name: Build Wazuh images
       run: |
-        if [ "${{ inputs.dev }}" = true ]; then
-          IMAGE_TAG="${{ inputs.image_tag }}-${{ inputs.reference }}"
-          ./build-images.sh -v ${{ inputs.image_tag }} -r $REVISION -d "dev" -rg $IMAGE_REGISTRY -m -ref ${{ inputs.reference }}
-        else
-          if [[ "$IMAGE_TAG" == *"-"* ]]; then
-            IFS='-' read -r -a tokens <<< "$IMAGE_TAG"
-            if [ -z "${tokens[1]}" ]; then
-              echo "Invalid image tag: $IMAGE_TAG"
-              exit 1
-            fi
-            DEV_STAGE=${tokens[1]}
-            WAZUH_VER=${tokens[0]}
-            if [ "${{ inputs.dev }}" = true ]; then
-              ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -rg $IMAGE_REGISTRY -m -ref ${{ inputs.reference }}
-            else 
-              ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -rg $IMAGE_REGISTRY -m
-            fi
-          else
-            ./build-images.sh -v $IMAGE_TAG -r $REVISION -rg $IMAGE_REGISTRY -m
+        if [[ "$IMAGE_TAG" == *"-"* ]]; then
+          IFS='-' read -r -a tokens <<< "$IMAGE_TAG"
+          if [ -z "${tokens[1]}" ]; then
+            echo "Invalid image tag: $IMAGE_TAG"
+            exit 1
           fi
+          DEV_STAGE=${tokens[1]}
+          WAZUH_VER=${tokens[0]}
+          if [ "${{ inputs.dev }}" = true ]; then
+            ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -rg $IMAGE_REGISTRY -m -ref ${{ inputs.reference }}
+          else 
+            ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -rg $IMAGE_REGISTRY -m
+          fi
+        else
+          ./build-images.sh -v $IMAGE_TAG -r $REVISION -rg $IMAGE_REGISTRY -m
         fi
         # Save .env file (generated by build-images.sh) contents to $GITHUB_ENV
         ENV_FILE_PATH="../.env"
