comment out block for testing purposes

diff --git a/.github/workflows/Procedure_push_docker_images.yml b/.github/workflows/Procedure_push_docker_images.yml
--- a/.github/workflows/Procedure_push_docker_images.yml
+++ b/.github/workflows/Procedure_push_docker_images.yml
@@ -97,64 +97,64 @@ jobs:
       with:
         ref: ${{ inputs.docker_reference }}
 
-    - name: free disk space
-      uses: ./.github/free-disk-space
+    # - name: free disk space
+    #   uses: ./.github/free-disk-space
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
+    # - name: Set up QEMU
+    #   uses: docker/setup-qemu-action@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+    # - name: Set up Docker Buildx
+    #   uses: docker/setup-buildx-action@v3
 
-    - name: Configure aws credentials
-      if: ${{ inputs.dev == true }}
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        role-to-assume: ${{ secrets.AWS_IAM_DOCKER_ROLE }}
-        aws-region: "${{ secrets.AWS_REGION }}"
+    # - name: Configure aws credentials
+    #   if: ${{ inputs.dev == true }}
+    #   uses: aws-actions/configure-aws-credentials@v4
+    #   with:
+    #     role-to-assume: ${{ secrets.AWS_IAM_DOCKER_ROLE }}
+    #     aws-region: "${{ secrets.AWS_REGION }}"
 
-    - name: Log in to Amazon ECR
-      if: ${{ inputs.dev == true }}
-      uses: aws-actions/amazon-ecr-login@v2
+    # - name: Log in to Amazon ECR
+    #   if: ${{ inputs.dev == true }}
+    #   uses: aws-actions/amazon-ecr-login@v2
 
-    - name: Log in to Docker Hub
-      if: ${{ inputs.dev == false }}
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    # - name: Log in to Docker Hub
+    #   if: ${{ inputs.dev == false }}
+    #   uses: docker/login-action@v3
+    #   with:
+    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    - name: Build Wazuh images
-      run: |
-        IMAGE_TAG="${{ inputs.image_tag }}"
-        FILEBEAT_MODULE_VERSION=${{ inputs.filebeat_module_version }}
-        REVISION=${{ inputs.revision }}
+    # - name: Build Wazuh images
+    #   run: |
+    #     IMAGE_TAG="${{ inputs.image_tag }}"
+    #     FILEBEAT_MODULE_VERSION=${{ inputs.filebeat_module_version }}
+    #     REVISION=${{ inputs.revision }}
 
-        if [[ "$IMAGE_TAG" == *"-"* ]]; then
-          IFS='-' read -r -a tokens <<< "$IMAGE_TAG"
-          if [ -z "${tokens[1]}" ]; then
-            echo "Invalid image tag: $IMAGE_TAG"
-            exit 1
-          fi
-          DEV_STAGE=${tokens[1]}
-          WAZUH_VER=${tokens[0]}
-          ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -f $FILEBEAT_MODULE_VERSION -rg $IMAGE_REGISTRY -m
-        else
-          ./build-images.sh -v $IMAGE_TAG -r $REVISION -f $FILEBEAT_MODULE_VERSION -rg $IMAGE_REGISTRY -m
-        fi
+    #     if [[ "$IMAGE_TAG" == *"-"* ]]; then
+    #       IFS='-' read -r -a tokens <<< "$IMAGE_TAG"
+    #       if [ -z "${tokens[1]}" ]; then
+    #         echo "Invalid image tag: $IMAGE_TAG"
+    #         exit 1
+    #       fi
+    #       DEV_STAGE=${tokens[1]}
+    #       WAZUH_VER=${tokens[0]}
+    #       ./build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -f $FILEBEAT_MODULE_VERSION -rg $IMAGE_REGISTRY -m
+    #     else
+    #       ./build-images.sh -v $IMAGE_TAG -r $REVISION -f $FILEBEAT_MODULE_VERSION -rg $IMAGE_REGISTRY -m
+    #     fi
 
-        # Save .env file (generated by build-images.sh) contents to $GITHUB_ENV
-        ENV_FILE_PATH="../.env"
+    #     # Save .env file (generated by build-images.sh) contents to $GITHUB_ENV
+    #     ENV_FILE_PATH="../.env"
 
-        if [ -f $ENV_FILE_PATH ]; then
-          while IFS= read -r line || [ -n "$line" ]; do
-            echo "$line" >> $GITHUB_ENV
-          done < $ENV_FILE_PATH
-        else
-          echo "The environment file $ENV_FILE_PATH does not exist!"
-          exit 1
-        fi
-      working-directory: ./build-docker-images
+    #     if [ -f $ENV_FILE_PATH ]; then
+    #       while IFS= read -r line || [ -n "$line" ]; do
+    #         echo "$line" >> $GITHUB_ENV
+    #       done < $ENV_FILE_PATH
+    #     else
+    #       echo "The environment file $ENV_FILE_PATH does not exist!"
+    #       exit 1
+    #     fi
+    #   working-directory: ./build-docker-images
 
     - name: Image exists validation
       if: ${{ inputs.dev == false }}
