Modify curl and dgoss run

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -66,10 +66,15 @@ jobs:
       uses: aws-actions/amazon-ecr-login@v2
 
     - name: Execute Goss tests (wazuh-manager)
-      run: dgoss run ${{ env.WAZUH_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_IMAGE_VERSION }}
+      run: |
+        export GOSS_FILE=$GITHUB_WORKSPACE/.github/.goss.yaml
+        if [ ! -f "$GOSS_FILE" ]; then
+          echo "Goss file not found at $GOSS_FILE"
+          exit 1
+        fi
+        dgoss run ${{ env.WAZUH_REGISTRY }}/wazuh/wazuh-manager:${{ env.WAZUH_IMAGE_VERSION }}
       env:
         GOSS_SLEEP: 30
-        GOSS_FILE: .github/.goss.yaml
 
   check-single-node:
     runs-on: ubuntu-22.04
@@ -95,7 +100,7 @@ jobs:
     - name: Create single node certficates
       run: |
         wazuh_certs_tool_url=$(aws s3 presign s3://${{ vars.AWS_S3_BUCKET_DEV }}/development/wazuh/5.x/secondary/installation-assistant/${{ env.WAZUH_IMAGE_VERSION }}/wazuh-certs-tool.sh --expires-in 3600 --region us-west-1)
-        curl -sO $wazuh_certs_tool_url
+        curl -sL "$wazuh_certs_tool_url" -o ./wazuh-certs-tool.sh
         cat > config.yml <<EOF
         nodes:
           # Wazuh indexer server nodes
@@ -257,7 +262,7 @@ jobs:
     - name: Create multi node certficates
       run: |
         wazuh_certs_tool_url=$(aws s3 presign s3://${{ vars.AWS_S3_BUCKET_DEV }}/development/wazuh/5.x/secondary/installation-assistant/${{ env.WAZUH_IMAGE_VERSION }}/wazuh-certs-tool.sh --expires-in 3600 --region us-west-1)
-        curl -sO $wazuh_certs_tool_url
+        curl -sL "$wazuh_certs_tool_url" -o ./wazuh-certs-tool.sh
         cat > config.yml <<EOF
         nodes:
         # Wazuh indexer server nodes
