Test CI

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -100,12 +100,16 @@ jobs:
       env:
         TOKEN: $(curl -s -u wazuh-wui:MyS3cr37P450r.*- -k -X GET "https://0.0.0.0:55000/security/user/authenticate?raw=true")
 
-    - name: check docker ps
-      run: docker ps
-
     - name: Check errors in ossec.log
       run: |
-       docker exec single-node_wazuh.manager_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -e "ERR||WARN||CRIT"'
+       log=$(docker exec multi-node_wazuh.master_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -E "ERR||WARN||CRIT"')
+       if [[ -z "$log" ]]; then
+        echo "No errors in master ossec.log"
+       else
+        echo "Errors in master ossec.log:"
+        echo "${log}"
+        exit 1
+       fi
 
     - name: Check filebeat output
       run: |
@@ -213,7 +217,7 @@ jobs:
 
     - name: Check errors in ossec.log
       run: |
-       log1=$(docker exec multi-node_wazuh.master_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -E "ERR|WARN|CRIT"')
+       log1=$(docker exec multi-node_wazuh.master_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -E "ERR||WARN||CRIT"')
        if [[ -z "$log1" ]]; then
         echo "No errors in master ossec.log"
        else
@@ -221,7 +225,7 @@ jobs:
         echo "${log1}"
         exit 1
        fi
-       log2=$(docker exec multi-node_wazuh.worker_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -E "ERR|WARN|CRIT"')
+       log2=$(docker exec multi-node_wazuh.worker_1 sh -c 'cat /var/ossec/logs/ossec.log | grep -E "ERR||WARN||CRIT"')
        if [[ -z "${log2}" ]]; then
         echo "No errors in worker ossec.log"
        else
